---
- name: Ensure ansible user is created.
  user:
    name: "{{ automated_user }}"
    create_home: true

- name: Grant sudo access to ansible user.
  copy:
    dest: "/etc/sudoers.d/{{ automated_user }}"
    content: "{{ automated_user }} ALL=(ALL) NOPASSWD: ALL"
    mode: "0440"
    validate: "visudo -cf %s"

- name: Ensure SSH key for ansible user is present.
  authorized_key:
    user: "{{ automated_user }}"
    state: present
    key: "{{ lookup('file', '{{ ssh_pub_key_location }}') }}"

- name: Create custom group.
  group:
    name: "{{ item }}"
    state: present
  with_items: "{{ custom_new_groups }}"

- name: Create custom users.
  user:
    name: "{{ item.user }}"
    create_home: true
    groups: "{{ item.groups }}"
    system: "{{ item.system }}"
    shell: "{{ item.shell }}"
  with_items: "{{ custom_new_users }}"
