---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache.
      package:
        update_cache: true
        cache_valid_time: 600

  roles:
    - role: rafael-c-alexandre.provision
