---
name: CI

'on':
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  ci:
    uses: rafael-c-alexandre/ansible-roles-devops/.github/workflows/ci.yml@main
    with:
      extra_molecule_args: "-- -e ssh_pub_key_location=.github/workflows/ci.pub"
